services:
  postgres:
    image: postgres:16
    container_name: thmanyah-postgres
    environment:
      POSTGRES_DB: thmanyah
      POSTGRES_USER: thmanyah
      POSTGRES_PASSWORD: thmanyah
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: thmanyah-meilisearch
    environment:
      MEILI_MASTER_KEY: thmanyah
      MEILI_ENV: development
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  postgres_data:
  meili_data:
