services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thmanyah-app
    environment:
      DATABASE_URL: postgresql://thmanyah:thmanyah@postgres:5432/thmanyah?schema=public
      MEILI_HOST: http://meilisearch:7700
      MEILI_API_KEY: 9940a8b9-16f5-419b-a354-a122ab66c34d
      STUDIO_API_KEY: ee335e8b-d763-46f4-a43b-58237dc67415
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - meilisearch
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
  postgres:
    image: postgres:16
    container_name: thmanyah-postgres
    environment:
      POSTGRES_DB: thmanyah
      POSTGRES_USER: thmanyah
      POSTGRES_PASSWORD: thmanyah
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: thmanyah-meilisearch
    environment:
      MEILI_MASTER_KEY: 9940a8b9-16f5-419b-a354-a122ab66c34d
      MEILI_ENV: development
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  postgres_data:
  meili_data:
