version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: thmanyah-postgres
    environment:
      POSTGRES_DB: thmanyah
      POSTGRES_USER: thmanyah
      POSTGRES_PASSWORD: thmanyah
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
